// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCENiNviLEfwpS-gbvzQG4BucXydP934rc',
    appId: '1:715605142216:web:81f10c6b685841b63593fd',
    messagingSenderId: '715605142216',
    projectId: 'flutter-task-c5ec9',
    authDomain: 'flutter-task-c5ec9.firebaseapp.com',
    storageBucket: 'flutter-task-c5ec9.firebasestorage.app',
    measurementId: 'G-ET75J0F45K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMeE9i_QPm0yXv83WioQCAG9k8Qc4CZpQ',
    appId: '1:715605142216:android:1ca75bc5c186a8483593fd',
    messagingSenderId: '715605142216',
    projectId: 'flutter-task-c5ec9',
    storageBucket: 'flutter-task-c5ec9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDapRPaUSSRmN6x09Hn9mF9L7Jil_hNdXI',
    appId: '1:715605142216:ios:d068e4c065c6525d3593fd',
    messagingSenderId: '715605142216',
    projectId: 'flutter-task-c5ec9',
    storageBucket: 'flutter-task-c5ec9.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDapRPaUSSRmN6x09Hn9mF9L7Jil_hNdXI',
    appId: '1:715605142216:ios:d068e4c065c6525d3593fd',
    messagingSenderId: '715605142216',
    projectId: 'flutter-task-c5ec9',
    storageBucket: 'flutter-task-c5ec9.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCENiNviLEfwpS-gbvzQG4BucXydP934rc',
    appId: '1:715605142216:web:97f6cf05731e88383593fd',
    messagingSenderId: '715605142216',
    projectId: 'flutter-task-c5ec9',
    authDomain: 'flutter-task-c5ec9.firebaseapp.com',
    storageBucket: 'flutter-task-c5ec9.firebasestorage.app',
    measurementId: 'G-9Q99JQBLNH',
  );
}
